name: flutter_web_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  geolocator: ^14.0.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
flutter:
  assets:
    - assets/icons/
  uses-material-design: true


