// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1c9g7Rz2buziMV49o9Q9X-0HiI-LJSBQ',
    appId: '1:209859432695:web:eed6f954e918a6f85683f2',
    messagingSenderId: '209859432695',
    projectId: 'weather-app-cde77',
    authDomain: 'weather-app-cde77.firebaseapp.com',
    storageBucket: 'weather-app-cde77.firebasestorage.app',
    measurementId: 'G-NW6V5LX3H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsq4A3JDDdbzB21W-i4jmYuwFVadwD3Yk',
    appId: '1:209859432695:android:b89e080ec826816d5683f2',
    messagingSenderId: '209859432695',
    projectId: 'weather-app-cde77',
    storageBucket: 'weather-app-cde77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfu-YrrvIHh-P5nAEyAJ5LNXBIJ81of2Y',
    appId: '1:209859432695:ios:151b585ea658b7325683f2',
    messagingSenderId: '209859432695',
    projectId: 'weather-app-cde77',
    storageBucket: 'weather-app-cde77.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebApp',
  );
}
